# Generated by Django 3.1.5 on 2021-01-07 16:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.IntegerField(help_text='Invoice #')),
                ('sequence_number_prefix', models.CharField(blank=True, help_text='Prefix for envoice #', max_length=5)),
                ('invoice_date', models.DateField(default=datetime.date.today, help_text='Invoice date')),
                ('due_date', models.DateField(default=datetime.date.today, help_text='Due date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('sequence_number_prefix', 'sequence_number')},
            },
        ),
    ]
