# Generated by Django 3.1.5 on 2021-01-25 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoice_creator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='currency_label',
            field=models.CharField(default='NULL', help_text='Currency for the invoice', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sequence_number_prefix',
            field=models.CharField(blank=True, help_text='Prefix for invoice #', max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('sequence_number_prefix', 'sequence_number', 'user')},
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(help_text='Item id', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Product name')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Item price - unit cost', max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('id', 'name', 'user')},
            },
        ),
    ]
