# Generated by Django 3.1.5 on 2021-01-25 16:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoice_creator', '0002_auto_20210125_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('sequence_number_prefix', 'sequence_number', 'owner')},
        ),
    ]
