# Generated by Django 3.1.5 on 2021-01-26 12:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.IntegerField(help_text='Invoice #')),
                ('sequence_number_prefix', models.CharField(blank=True, help_text='Prefix for invoice #', max_length=5)),
                ('invoice_date', models.DateField(default=datetime.date.today, help_text='Invoice date')),
                ('due_date', models.DateField(default=datetime.date.today, help_text='Due date')),
                ('currency_label', models.CharField(help_text='Currency for the invoice', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(help_text='Item id', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Product name')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Item price', max_digits=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('id', 'name', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='number of items')),
                ('overwritte_price', models.DecimalField(blank=True, decimal_places=2, help_text='Custom item price', max_digits=10, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.invoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='items',
            field=models.ManyToManyField(through='core.InvoiceEntry', to='core.Item'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('sequence_number_prefix', 'sequence_number', 'owner')},
        ),
    ]
