# Generated by Django 3.1.5 on 2021-01-27 20:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=1024)),
                ('company_address', models.CharField(max_length=1024)),
                ('city', models.CharField(max_length=1024)),
                ('state', models.CharField(max_length=1024)),
                ('country', models.CharField(max_length=1024)),
                ('zip', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.CharField(blank=True, help_text='Invoice #', max_length=100, unique=True)),
                ('invoice_date', models.DateField(default=datetime.date.today, help_text='Invoice date')),
                ('due_date', models.DateField(blank=True, help_text='Due date')),
                ('currency_label', models.CharField(help_text='Currency for the invoice eg. USD, EUR, $, €', max_length=5)),
                ('notes', models.TextField(blank=True, help_text='Additional informations about invoice')),
                ('terms', models.TextField(blank=True, help_text='Additional informations about invoice', verbose_name='Terms & Conditions')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, help_text='Your name and last name', max_length=100, null=True)),
                ('company_details', models.ForeignKey(help_text='Details of your company', on_delete=django.db.models.deletion.CASCADE, to='core.companydetails')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.CharField(help_text='Item id', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Product name')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, help_text='Item price', max_digits=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('item_id', 'name', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_to', models.CharField(blank=True, help_text='Recipient full name', max_length=100, null=True)),
                ('client_company_details', models.ForeignKey(help_text='Details of the client company', on_delete=django.db.models.deletion.CASCADE, to='core.companydetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='number of items')),
                ('overwrite_unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Custom item price', max_digits=10, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.invoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='items',
            field=models.ManyToManyField(related_name='entries', through='core.InvoiceEntry', to='core.Item'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.invoicerecipient'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('sequence_number', 'owner')},
        ),
    ]
