# Generated by Django 3.1.5 on 2021-01-25 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.IntegerField(help_text='Invoice #')),
                ('sequence_number_prefix', models.CharField(blank=True, help_text='Prefix for invoice #', max_length=5)),
                ('invoice_date', models.DateField(default=datetime.date.today, help_text='Invoice date')),
                ('due_date', models.DateField(default=datetime.date.today, help_text='Due date')),
                ('currency_label', models.CharField(help_text='Currency for the invoice', max_length=5)),
            ],
            options={
                'unique_together': {('sequence_number_prefix', 'sequence_number')},
            },
        ),
    ]
