# Generated by Django 3.1.5 on 2021-01-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='items',
            field=models.ManyToManyField(related_name='items', through='core.InvoiceEntry', to='core.Item'),
        ),
    ]
