# Generated by Django 3.1.5 on 2021-01-26 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_invoice_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('sequence_number_prefix', 'sequence_number', 'owner')},
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(help_text='Item id', primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Product name')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Item price - unit cost', max_digits=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('id', 'name', 'owner')},
            },
        ),
    ]
