# Generated by Django 3.1.5 on 2021-01-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210126_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='items',
            field=models.ManyToManyField(related_name='items', to='core.Item'),
        ),
    ]
